FROM jenkins/jenkins:lts

USER root

RUN apt update

RUN apt install -y apt-transport-https ca-certificates curl gnupg2

RUN install -m 0755 -d /etc/apt/keyrings
RUN curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc
RUN chmod a+r /etc/apt/keyrings/docker.asc

# Add Docker repository to APT sources
RUN echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian \
  $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
  tee /etc/apt/sources.list.d/docker.list > /dev/null

RUN apt update && apt-get install -y docker-ce-cli

# Create the docker group, change the group number to the number from this 'getent group docker'
RUN groupadd -g 995 docker

# Add jenkins user to the docker group
RUN usermod -aG docker jenkins

RUN apt install chromium -y

# Switch to jenkins user
USER jenkins

ENTRYPOINT ["/usr/bin/tini", "--", "/usr/local/bin/jenkins.sh"]